"""PhysiClaw's single data root.

All persistent state — calibration, memory, jobs, model cache, logs —
lives under ``~/.physiclaw/``. Override with ``PHYSICLAW_HOME`` (read once
at import, so set it *before* the first ``import physiclaw`` in tests).

Layout::

    ~/.physiclaw/
    ├── calibration/{bundle.json, cache/}
    ├── memory/{memory.md, USER.md, YYYY-MM-DD.md}
    ├── jobs/jobs.md
    ├── models/omniparser_icon_detect/model.onnx
    ├── skills/<name>/SKILL.md           (user-authored; overrides built-in)
    ├── official/{source.json, skills/, .sync-state.json}  (synced official pack)
    ├── cache/update.json                (update-notice stage marker; Phase B→A)
    ├── learned/pitfalls/{pitfalls.md, history.jsonl}  (agent-flagged traps; add_pitfall)
    ├── screen-layout/{layout.json, layout.md}  (learned on first run by the `screen-layout` skill)
    ├── ui-presets/system-keyboard.md    (generated by `setup phone`)
    ├── snapshots/, screenshots/, tool_calls/, raw_camera/  (debug dumps; `physiclaw clear`)
    ├── run/server.json                  (live server pid+host+port; cleared on exit)
    └── log/
        ├── engine/
        │   ├── engine-YYYY-MM-DD.log    (human narrative, all sessions of a day)
        │   └── sessions/{README.md, <sid>/{events.jsonl, wire.jsonl, summary.json, images/}}
        ├── runtime/runtime-YYYY-MM-DD.log
        └── claude/claude-YYYY-MM-DD.log
"""

import json
import os
from importlib.resources import files as _pkg_files
from pathlib import Path

from physiclaw.common.text import read_text

HOME: Path = Path(os.environ.get("PHYSICLAW_HOME", "~/.physiclaw")).expanduser()
LOG_DIR: Path = HOME / "log"


def ensure_dirs() -> None:
    """Create HOME and LOG_DIR. Safe to call repeatedly."""
    HOME.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def model_cache() -> Path:
    return HOME / "models"


def cache_dir() -> Path:
    """Scratch space for background-staged/prefetched artifacts — currently the
    update-notice stage marker (``cache/update.json``, written by Phase B and
    consumed by Phase A at the next startup). Safe to delete; regenerated on
    demand. Distinct from uv's own wheel cache, which the marker points into."""
    return HOME / "cache"


def omniparser_onnx() -> Path:
    return model_cache() / "omniparser_icon_detect" / "model.onnx"


def calibration_dir() -> Path:
    """Arm/camera/screen calibration state — ``bundle.json`` + ``cache/``.
    Cleared by ``physiclaw reset`` so a new phone gets re-calibrated."""
    return HOME / "calibration"


def calibration_bundle() -> Path:
    return calibration_dir() / "bundle.json"


def load_calibration_bundle() -> dict | None:
    """Read+parse ``calibration/bundle.json``. None on missing/unreadable/invalid."""
    p = calibration_bundle()
    if not p.exists():
        return None
    try:
        data = json.loads(read_text(p))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def calibration_cache_dir() -> Path:
    return calibration_dir() / "cache"


def snapshots_dir() -> Path:
    return HOME / "snapshots"


def screenshots_dir() -> Path:
    return HOME / "screenshots"


def tool_calls_dir() -> Path:
    return HOME / "tool_calls"


def raw_camera_dir() -> Path:
    return HOME / "raw_camera"


def jobs_file() -> Path:
    return HOME / "jobs" / "jobs.md"


def memory_dir() -> Path:
    return HOME / "memory"


def skills_dir() -> Path:
    return HOME / "skills"


def official_dir() -> Path:
    """Official skill pack synced from the site (``physiclaw skills sync
    official``). Kept separate from ``skills_dir()`` (user-authored): the
    sync owns this tree wholesale — an atomic swap replaces ``official/skills``
    on every run, so anything a user drops here is blown away. Layout::

        official/
        ├── source.json       (upstream manifest, extracted verbatim)
        ├── skills/<name>/…    (the mounted skills)
        └── .sync-state.json   (client-written sync bookkeeping)
    """
    return HOME / "official"


def official_skills_dir() -> Path:
    """The mounted official skills tree — a ``<name>/SKILL.md`` root like
    ``skills_dir()``. Empty until the first successful ``skills sync official``."""
    return official_dir() / "skills"


def pitfalls_dir() -> Path:
    """Agent-flagged turn-wasting traps — ``learned/pitfalls/pitfalls.md`` (the
    live list, always injected into SYSTEM after user skills) plus an
    append-only ``history.jsonl``. The agent only *appends* ≤3 items per
    long DONE session; a post-session curator consolidates and caps the list.
    Pitfalls-only (no how-to) sidesteps the self-praise that poisons an
    agent-authored 'working flow'."""
    return HOME / "learned" / "pitfalls"


def builtin_skills_dir() -> Path:
    """Flat-``.md`` skills shipped inside the wheel — the out-of-the-box
    baseline every install gets. Discovery layers ``skills_dir()`` (user)
    on top, so a home skill of the same name overrides a built-in one."""
    # Locate the shipped `physiclaw/agent/skills/` resource dir the same
    # way vision does for its bundled templates (see `core.vision.keyboard`)
    # — resilient to where this module lives in the package tree.
    return Path(str(_pkg_files("physiclaw.agent") / "skills"))


def screen_layout_dir() -> Path:
    """Learned key input-box + on-screen-keyboard bboxes (Spotlight search,
    chat input with/without keyboard), captured on first run by the
    ``screen-layout`` skill via ``report_screen_layout``. Empty until
    learned — the runtime keys first-run setup on that emptiness."""
    return HOME / "screen-layout"


def screen_layout_json() -> Path:
    return screen_layout_dir() / "layout.json"


def screen_layout_md() -> Path:
    return screen_layout_dir() / "layout.md"


def ui_presets_dir() -> Path:
    return HOME / "ui-presets"


def runtime_state_file() -> Path:
    return HOME / "run" / "server.json"


def claude_log_dir() -> Path:
    return LOG_DIR / "claude"


def engine_log_dir() -> Path:
    return LOG_DIR / "engine"


def engine_sessions_dir() -> Path:
    """Per-session artifact dirs: sessions/<sid>/{events.jsonl, wire.jsonl,
    summary.json, images/}."""
    return engine_log_dir() / "sessions"


def runtime_log_dir() -> Path:
    return LOG_DIR / "runtime"
